# Generated by Django 5.1.4 on 2025-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0002_alter_foodentry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='dish',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='dishes',
            field=models.ManyToManyField(to='foodwaste.dish'),
        ),
    ]
