# Generated by Django 5.1.4 on 2025-04-09 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0003_remove_foodentry_dish_foodentry_dishes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='waste_amount',
        ),
        migrations.CreateModel(
            name='DishWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_percentage', models.PositiveSmallIntegerField(choices=[(0, '0%'), (25, '25%'), (50, '50%'), (75, '75%'), (100, '100%')])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodwaste.dish')),
                ('food_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_wastes', to='foodwaste.foodentry')),
            ],
            options={
                'unique_together': {('food_entry', 'dish')},
            },
        ),
    ]
