# Generated by Django 5.1.4 on 2025-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste', '0004_remove_foodentry_liked_remove_foodentry_waste_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='eaten_amount',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='rating',
        ),
        migrations.AddField(
            model_name='dishwaste',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], default=0),
        ),
    ]
